language: go

go:
  - 1.4
  - 1.5

install:
  - go get github.com/mattn/goveralls
  - go get github.com/funny/utest

script:
  - go vet -x
  - go test -v -bench=.
  - go test -covermode=count -coverprofile=profile.cov .

after_script:
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci